django_sample/clade_predictor/urls.py
from django.urls import path
from . import views

app_name = 'clade_predictor'

urlpatterns = [
    path("home/", views.home, name = 'home'),
    path("contact/", views.contact, name = 'contact'),
    path("how_to_use/", views.how_to_use, name = 'how_to_use')
    ]

django_sample/django_sample/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clade_predictor/', include('clade_predictor.urls')),
    path('', RedirectView.as_view(url='/clade_predictor/home', permanent=False))
]

django_sample/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">



<style>


.submit-button {
  background-color: #4ac4cf;
  border: none;
  color: black;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 8px;
}

.submit-button:hover {
  background-color: #3fabb5;
}

table {
  border-collapse: collapse;
  width: 100%;
  max-width: 800px;
  margin: 0;
}

th, td {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

th {
  background-color: #f2f2f2;
}
.content-rectangle {
    border: 2px dashed #ccc;
    background-color: rgba(255, 255, 255, 0.5);
    padding: 20px;
    border-radius: 10px;
    width: 500px;
    margin: 20px 0;
    float: left; /* Aligns to the left of the screen */
  }
  
  form {
    display: flex;
    flex-direction: column;
    gap: 20px;
  }
  
  .form-group {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  
  #drop-area {
    border: 2px dashed #ccc;
    border-radius: 8px;
    padding: 20px;
    text-align: center;
    cursor: pointer;
    transition: 0.3s ease;
  }
  
  #drop-area p {
    margin: 0;
    font-size: 14px;
    color: #666;
  }
  
  #drop-area.highlight {
    border-color: #6c63ff;
    background-color: #f0f0ff;
  }
  
  .submit-button {
    background-color: #4ac4cf;
    border: none;
    color: black;
    padding: 12px 24px;
    text-align: center;
    font-size: 16px;
    cursor: pointer;
    border-radius: 8px;
    width: fit-content;
    align-self: center;
  }
  
  .submit-button:hover {
    background-color: #3fabb5;
  }
  


</style>


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MPXV</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/d4ed401b86.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="master_bts_forms.css">


    <nav class="navbar avbar-light navbar-expand-lg" style="background-color: #F0F8FF;">
      <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="navbar-brand d-flex align-items-center" href="{% url 'clade_predictor:home' %}">
                  <img src="https://raw.githubusercontent.com/gustavsganzerla/mpxv_clade_prediction/refs/heads/main/django_sample/clade_predictor/static/clade_predictor/images/logo.png" alt="Logo" width="75" height="75" class="d-inline-block align-text-top me-2">
                </a>
                <a class="nav-link" href="{% url 'clade_predictor:how_to_use' %}">How to Use</a>
                  <a class="nav-link">About</a>
                  <a class="nav-link" href="{% url 'clade_predictor:contact' %}">Contact</a>
              </div>
              
          </div>
          <div class="image-container ms-auto">
            <div class="image-container ms-auto">
                <a href = "https://www.dal.ca/" target = "_blank">
                <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/dal.png" alt="Dal Logo" width="75" height="75">
                </a>
            </div>
            
        </div>
      </div>
    </nav>
</head>
<body style="display: flex; flex-direction: column; min-height: 100vh;">
    

  <div class="flex-grow-1">
    {% block content %}
    
    {% endblock %}
  </div>
  </body>

  <footer class="bg-secondary text-black text-center" style="background-color: #F0F8FF !important;">
    <a href = "https://www.dal.ca/" target = "_blank">
    <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/dal_fm.png" alt="Dal Logo" width="250" height="100">
    </a>
    <p style="margin-bottom: 3px;">Department of Microbiology & Immunology</p>
    <p style="margin-bottom: 3px;">&copy; 2023-2024 Laboratory of Emerging Infectious Diseases</p>
    <p style="margin-bottom: 3px;">
        <a href="https://github.com/gustavsganzerla/mpp">
            <i class="fab fa-github"></i> GitHub
        </a>
    </p>
</footer>



</html>